language: c
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.7"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  #- ln -s $PWD /usr/local/share/arduino/libraries/Adafruit_FONA
  - arduino --install-library "Adafruit SleepyDog Library","Adafruit FONA Library"
  # - arduino --install-boards esp8266:esp8266 --save-prefs
  - arduino --install-library "SparkFun BME280" --save-prefs
  - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
  - arduino --get-pref
script:
  #- arduino -v --verbose-build --verify --board esp8266:esp8266:generic $PWD/arduino/esp8266/esp8266.ino
  - build_platform esp8266
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: change
