language: c
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.7"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.7-linux64.tar.xz
  - tar xf arduino-1.8.7-linux64.tar.xz
  - sudo mv arduino-1.8.7 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
  - arduino --pref "boardsmanager.additional.urls=https://github.com/esp8266/Arduino/releases/download/2.4.2/package_esp8266com_index.json" --save-prefs
install:
  #- ln -s $PWD /usr/local/share/arduino/libraries/Adafruit_FONA
  - arduino --install-library "Adafruit SleepyDog Library","Adafruit FONA Library"
  - arduino --install-boards esp8266:esp8266 --save-prefs
  - arduino --install-library "SparkFun BME280" --save-prefs
  - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
  - arduino --get-pref
script:
  - build_main_platforms
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: change
